### PR TITLE
fix: responsive issue of search bar

### LINKED ISSUE #227: [Bug]: Responsive issue of inputs in home screen.
### Project

Website (Potter DB Search)

### Bug description

The inputs align in a single line on mobile devices affecting UX.
image

### Expected Behavior

Inputs to be aligned below each other for improved visibility, and better handling of by the user.

### Steps to reproduce

Open homepage in mobile device.

### Screenshots

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by ST1LLWATER**
- [X] I have read and agree to the [Code of Conduct](https://github.com/danielschuster-muc/potter-db/blob/master/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/danielschuster-muc/potter-db/blob/master/CONTRIBUTING.md).

## Pull Request Type

- [X] Bug fix #227 

## Summary
Fixed responsive issues of search bar, button alignment and widths.
changes

### CODE REVIEW

File: frontend/src/components/pages/index/SearchBar.js [hunk 1]
```diff
@@ -60,7 +80,7 @@ const SearchBar = () => {
         label="Type"
         value={searchType}
         onChange={handleChangeSearchType}
-        sx={{ mx: 2 }}
+        // sx={{ mx: 2 }}
```
Comment (danielschuster-muc) [inline frontend/src/components/pages/index/SearchBar.js:83]: Can you please remove this comment?

**Review by danielschuster-muc — APPROVED** [review]
Thank you for your contribution to Potter DB!
